/*INSERTAR_CENTRO*/

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE INSERT_CENTROS(
	I_NOMBRE VARCHAR2,
	I_PROVINCIA VARCHAR2)
 IS
	N_REPETIDO EXCEPTION;
 BEGIN
  	DECLARE
	  V_NOMBRE centros.nombre%TYPE; 
	BEGIN
	  SELECT nombre INTO V_NOMBRE FROM CENTROS
		WHERE upper(nombre) = UPPER(I_NOMBRE);
      IF SQL%FOUND THEN
	      RAISE N_REPETIDO;  
      END IF;
	EXCEPTION
	  WHEN NO_DATA_FOUND THEN
	    NULL;
	  WHEN TOO_MANY_ROWS THEN
	     RAISE_APPLICATION_ERROR ('-20002','Error: Estás insertando más columnas que las existentes en la tabla');
	END;		
    INSERT INTO CENTROS (nombre,provincia) VALUES (UPPER(I_NOMBRE),UPPER(I_PROVINCIA));
	IF SQL%FOUND
	THEN
		COMMIT;
	END IF;
 EXCEPTION
  WHEN N_REPETIDO THEN
    RAISE_APPLICATION_ERROR ('-20001','Ya existe un centro con el nombre '|| I_NOMBRE);
END INSERT_CENTROS;


/*BUSCAR_CENTRO_POR_NOMBRE*/

CREATE OR REPLACE PROCEDURE BUSCAR_CENTRO_POR_NOMBRE (
	G_NOMBRE VARCHAR2, p_id out Number)
 IS
	N_NOTFOUND EXCEPTION;
BEGIN

	  SELECT id INTO p_id FROM CENTROS
		WHERE ID = (SELECT ID FROM CENTROS WHERE NOMBRE = UPPER(G_NOMBRE));
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR ('-20001','No existe ningun centro con el nombre '|| G_NOMBRE);
    
END BUSCAR_CENTRO_POR_NOMBRE;

EXECUTE INSERT_CENTROS ('Bilbo','Bolson');
EXECUTE BUSCAR_CENTRO_POR_NOMBRE ('Bilbo');



SELECT * FROM CENTROS;

DELETE FROM CENTROS WHERE ID=56;


