CREATE OR REPLACE PROCEDURE VISUALIZAR_DATOS_CENTRO(P_ID IN NUMBER, NUMERO OUT NUMBER, T_CURSOR OUT Sys_Refcursor) IS
BEGIN
  SELECT COUNT(*) INTO NUMERO FROM TRABAJADORES WHERE IDCENTRO = P_ID;
  OPEN T_CURSOR FOR 'SELECT * INTO T_CURSOR FROM CENTROS WHERE ID = P_ID';
END;